### ISSUE TITLE
Deserializing a JSON

### ISSUE THREAD

**Issue by aborruso** [Yord/json-stream#3] opened 2020-01-16 09:14 UTC
Hi,
first of all thank you for this project!!

When I run this command on [this JSON](https://gist.githubusercontent.com/aborruso/10dc121829ecc69ad68ede91b6e39120/raw/891b7a2cac10e0e46f96a2afa160b4c325b4a1b4/input.json)

```
pxi --deserializer json --serializer csv <input.json
```

I have

```
Unexpected token , in JSON at position 2
```

Am I doing something wrong? Can I deserialize only not nested JSON input?

**Comment by Yord** [comment] 2020-01-16 10:55
Hi aborruso,

thank you for the issue.

First of all, let me supply you with a script that deserializes your JSON, so you can keep going:

```bash
pxi --chunker jsonObj --deserializer json --spaces 2 < input.json > output.json
```

The key is using a different `--chunker`. The default `line` chunker does not work since your JSON is formatted across several lines. The output should now be identical to the input, and this should fix reading in your JSON.

Next, let's talk about serializing this JSON into CSV. We have a complication to overcome, here: CSV is a "flat" format that usually does not allow tables as values, your JSON however, has nested objects. `pxi-dsv`'s `--allow-list-values` is exactly for that. If you supply it, the nested JSONs are put into CSV fields, but are still formatted as JSON strings:

```bash
pxi --chunker jsonObj --deserializer json --serializer csv --allow-list-values < input.json > output.csv
```

Because of the differences between the CSV and JSON formats, this is as far as `pxi` goes. Alternatively, you could use functions to transform your JSON to a "flat" object without nesting first, and then serialize it to CSV.

Hope this helps!

Cheers
Yord

PS: I will not close this issue for now, as I am investigating better error messaging than `Unexpected token , in JSON at position 2`.

**Comment by aborruso** [comment] 2020-01-16 11:07
Thank you very much

**Comment by Yord** [comment] 2020-01-16 20:59
I have just published `pxi` version 0.36.6. The error now reads:

```bash
Unexpected token , in JSON at position 2 (if the JSON is formatted over several lines, try using the jsonObj chunker)
```

Hopefully, this will help our fellow developers in the future. Thanks again for bringing this to my attention!

**Closed as completed** 2020-01-16 20:59 UTC

**Comment by horak** [comment] 2021-01-08 22:25
Hi folks.

I'm trying to do something similar, sans the serialization.

```$ pxi --chunker jsonObj --from json --to csv < african-20181028.01.json > test.csv```

This results in the following output. Is there another chunker that's necessary here or is my command simply incorrect? 

```Unexpected token  in JSON at position 11 (if the JSON is formatted over several lines, try using the jsonObj chunker)```

Thanks for taking a look!

**Comment by Yord** [comment] 2021-01-09 01:02
Hi horak,

your command looks fine and does work on the sample data that `pxi` uses in its examples.

E.g. the following works fine:

```bash
head -100 2019.jsonl | pxi --chunker jsonObj --from json --to csv
```

So the issue is hard to debug without seeing sample data from the `african-20181028.01.json` file. Can you maybe supply some sample data from that file?

Cheers
Yord
